networks:
  nestjs-auth-kit-test:

services:
  test-db:
    image: mysql
    ports:
      - "43306:3306"
    environment:
      MYSQL_USER: "nestjs-auth-kit"
      MYSQL_PASSWORD: "nestjs-auth-kit"
      MYSQL_ROOT_PASSWORD: "testdbpassword"
      MYSQL_DATABASE: "nestjs-auth-kit-test"
    networks:
      - nestjs-auth-kit-test