networks:
  nestjs-auth-kit:

services:
  mysql:
    image: mysql
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    networks:
      - nestjs-auth-kit

  test-db:
    image: mysql
    ports:
      - "43306:3306"
    environment:
      MYSQL_USER: "nestjs-auth-kit"
      MYSQL_PASSWORD: "nestjs-auth-kit"
      MYSQL_ROOT_PASSWORD: "testdbpassword"
      MYSQL_DATABASE: "nestjs-auth-kit-test"