services:
  test-db:
    image: mysql
    container_name: nestjs-auth-kit-test-db
    ports:
      - "43306:3306"
    environment:
      MYSQL_USER: "nestjs-auth-kit"
      MYSQL_PASSWORD: "nestjs-auth-kit"
      MYSQL_ROOT_PASSWORD: "testdbpassword"
      MYSQL_DATABASE: "nestjs-auth-kit-test"