export enum ExceptionCode {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_GOOGLE_LOGIN_ERROR = 'INVALID_GOOGLE_LOGIN_ERROR',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  NO_TOKEN = 'NO_TOKEN',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
}
